# Generated by Django 4.1 on 2022-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('age', models.DateField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('exp', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('gfrom', models.CharField(max_length=255, null=True)),
                ('gyear', models.DateField(null=True)),
                ('bimage', models.ImageField(null=True, upload_to='image')),
                ('certicate', models.ImageField(null=True, upload_to='certificate')),
                ('valid', models.BooleanField(default=True)),
                ('bcmgpa', models.IntegerField(null=True)),
                ('bach', models.DateField(null=True)),
                ('msc', models.DateField(null=True)),
                ('phd', models.DateField(null=True)),
                ('mimage', models.ImageField(null=True, upload_to='certificate')),
                ('pimage', models.ImageField(null=True, upload_to='certificate')),
                ('mcmgpa', models.IntegerField(null=True)),
                ('pcmgpa', models.IntegerField(null=True)),
            ],
        ),
    ]
